/*
 * USART_Config.h
 *
 *  Created on: Sep 1, 2025
 *      Author: JETT
 */

#ifndef MCAL_USART_USART_CONFIG_H_
#define MCAL_USART_USART_CONFIG_H_



/* WORD_SIZE --OPTIONS
 WORD_8BIT_SIZE   0
 WORD_9BIT_SIZE   1
*/
#define WORD_SIZE1 WORD_8BIT_SIZE
#define WORD_SIZE2 WORD_8BIT_SIZE
#define WORD_SIZE6 WORD_8BIT_SIZE

/* PARITY --OPTIONS
 PARITY_ENABLE    0
 PARITY_DISABLE   1
*/
#define PARTIY_CONTROL1  PARTIY_DISABLE
#define PARTIY_CONTROL2  PARTIY_DISABLE
#define PARTIY_CONTROL6  PARTIY_DISABLE
/* PARITY_SELECTION --OPTIONS
 EVEN_PARITY      0
 ODD_PARITY       1
 */
#define PARITY_SELECTION1  ODD_PARITY
#define PARITY_SELECTION2  ODD_PARITY
#define PARITY_SELECTION6  ODD_PARITY

/* TC_INTERRUPT    --OPTIONS
 TC_ENABLE        0
 TC_DISABLE       1
 */
#define TC_INTERRUPT1   TC_DISABLE
#define TC_INTERRUPT2   TC_DISABLE
#define TC_INTERRUPT6   TC_DISABLE



#endif /* MCAL_USART_USART_CONFIG_H_ */
